import path from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import jest from "eslint-plugin-jest";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import spellcheck from "eslint-plugin-spellcheck";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";

/** * @type { Partial<import("@eslint/core").RuleConfig> } */
const jsRules = {
  "no-eval": "error",
  "no-unused-vars": "off",
  "no-console": "warn",
  "react/prop-types": "off",
  "react/jsx-indent": [0],
  "max-nested-callbacks": ["warn", 3],
  "no-alert": "error",
  "no-else-return": "warn",
  "jest/expect-expect": "off",
  "no-unsafe-finally": "off",
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": "warn",
  "spellcheck/spell-checker": [
    "warn",
    {
      identifiers: true,
      comments: true,
      strings: true,
      minLength: 4,
      skipIfMatch: [],
      skipWordIfMatch: [
        "http(s)?://[^s]*",
        "0x[0-9a-fx]{2,16}",
        "[0-9a-f]{4,32}",
        "Oauth2",
      ],
      skipWords: [
        "accessor",
        "allowfullscreen",
        "amazonaws",
        "apiversion",
        "ascii",
        "asciimath",
        "autoformat",
        "autosave",
        "autosaved",
        "autosaves",
        "autostart",
        "autosuggest",
        "azureblob",
        "backend",
        "beforeunload",
        "bioconductor",
        "blockquote",
        "bool",
        "booleans",
        "borderless",
        "bulleted",
        "calc",
        "cancellable",
        "cancelled",
        "charset",
        "chartpress",
        "cheatsheet",
        "checkbox",
        "ciyer",
        "ckeditor",
        "cktextarea",
        "clearfix",
        "cloudstorage",
        "codegen",
        "codemirror",
        "compat",
        "craco",
        "crosshair",
        "dagre",
        "dataset",
        "datasets",
        "dataverse",
        "datetime",
        "debounce",
        "debounced",
        "discoverability",
        "dismissible",
        "dockerfile",
        "dockerignore",
        "dropbox",
        "dropdown",
        "dropzone",
        "enum",
        "etag",
        "favicon",
        "fetchable",
        "firecrest",
        "formgenerator",
        "fortran",
        "frameborder",
        "frontend",
        "func",
        "gemoji",
        "gitlab",
        "gitter",
        "graphlib",
        "graphql",
        "grayscale",
        "hljs",
        "href",
        "hstack",
        "iframe",
        "iids",
        "impl",
        "integrations",
        "interruptable",
        "ipynb",
        "ipython",
        "isbot",
        "ispassword",
        "javascript",
        "jpeg",
        "jsonrpc",
        "jszip",
        "julia",
        "jumbotron",
        "jupyter",
        "katex",
        "kernelspec",
        "Keycloak",
        "kubernetes",
        "Lausanne",
        "linkify",
        "localhost",
        "mailto",
        "maintenances",
        "matcher",
        "mathbf",
        "mathjax",
        "mergerequests",
        "metadata_oauth",
        "mongodb",
        "monospace",
        "morgan",
        "mouseout",
        "mouseover",
        "multiline",
        "multipart",
        "mustermann",
        "namespace",
        "namespaces",
        "nbconvert",
        "nbextension",
        "nbformat",
        "nextcloud",
        "noopener",
        "noreferrer",
        "nowrap",
        "nteract",
        "ntlm",
        "nullable",
        "oauth2",
        "objectstores",
        "oidc",
        "onloadend",
        "onopen",
        "openapi",
        "openbis",
        "papermill",
        "pathname",
        "pdfjs",
        "pipeable",
        "pkce",
        "plaintext",
        "pluggable",
        "poller",
        "polybox",
        "popups",
        "prepend",
        "presentational",
        "profiler",
        "progressbar",
        "proxying",
        "Pupikofer",
        "pygments",
        "Ravey",
        "rclone",
        "rcloud",
        "react",
        "readme",
        "readonly",
        "rect",
        "redux",
        "reduxjs",
        "rehype",
        "remark2rehype",
        "renderer",
        "renderers",
        "renku",
        "renkulab",
        "replacer",
        "repo",
        "repos",
        "reproducibility",
        "rescaled",
        "resize",
        "reusability",
        "rproj",
        "rstudio",
        "scala",
        "scrollable",
        "selectautosuggest",
        "semibold",
        "serializable",
        "sftp",
        "shareability",
        "sharepoint",
        "sitemap",
        "slugify",
        "starrers",
        "statuspage",
        "stdout",
        "stockimages",
        "storages",
        "strikethrough",
        "sunsetting",
        "swiper",
        "tada",
        "telepresence",
        "textarea",
        "thead",
        "toastify",
        "toggler",
        "tokenizer",
        "tolerations",
        "toml",
        "tooltip",
        "tspan",
        "uiserver",
        "ulid",
        "uncompress",
        "unicode",
        "unlink",
        "unmount",
        "unschedulable",
        "unstar",
        "unstyled",
        "unsynced",
        "uploadable",
        "uploader",
        "uploadprogress",
        "urls",
        "validators",
        "versioned",
        "visibilities",
        "vstack",
        "webhook",
        "webhooks",
        "webkit",
        "webpack",
        "webworkers",
        "whitespace",
        "wip",
        "yaml",
        "youtube",
        "zenodo",
      ],
    },
  ],
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default defineConfig([
  globalIgnores([
    "**/*.css",
    "**/*.svg",
    "src/features/connectedServices/api/connectedServices.generated-api.ts",
    "src/features/dataConnectorsV2/api/data-connectors.api.ts",
    "src/features/dataConnectorsV2/api/doiResolver.generated-api.ts",
    "src/features/notifications/api/notifications.generated-api.ts",
    "src/features/cloudStorage/api/projectCloudStorage.generated-api.ts",
    "src/features/projectsV2/api/projectV2.api.ts",
    "src/features/searchV2/api/searchV2Api.generated-api.ts",
    "src/features/sessionsV2/api/computeResources.generated-api.ts",
    "src/features/sessionsV2/api/sessionLaunchersV2.generated-api.ts",
    "src/features/sessionsV2/api/sessionsV2.generated-api.ts",
    "src/features/usersV2/api/users.generated-api.ts",
  ]),
  {
    files: ["**/*.js", "**/*.jsx"],
    extends: [
      js.configs.recommended,
      ...compat.extends(
        "plugin:react/recommended",
        "plugin:react/jsx-runtime",
        "plugin:jest/recommended",
        "prettier"
      ),
    ],
    plugins: {
      react,
      "react-hooks": reactHooks,
      jest,
      spellcheck,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        ...jest.environments.globals.globals,
      },
      parser: tsParser,
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: jsRules,
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    extends: [
      js.configs.recommended,
      ...compat.extends(
        "plugin:@typescript-eslint/recommended",
        "plugin:react/recommended",
        "plugin:react/jsx-runtime",
        "plugin:react-hooks/recommended",
        "plugin:jest/recommended",
        "prettier"
      ),
    ],
    plugins: {
      "@typescript-eslint": typescriptEslint,
      react,
      "react-hooks": reactHooks,
      jest,
      spellcheck,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        ...jest.environments.globals.globals,
      },
      parser: tsParser,
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: {
        project: ["./tsconfig.json"],
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": "warn",
      ...jsRules,
    },
  },
]);
