const JobStatusMap = {
  ENQUEUED: "ENQUEUED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED"
};

//WE SHOULD ADD HERE GENERAL JOB MONITORING FUNCTIONS/COMPONENTS (IN THE FUTURE)

export { JobStatusMap };
