export const groups = [
  {
    id: 53,
    web_url: "https://dev.renku.ch/gitlab/groups/advanced-tutorial",
    name: "advanced-tutorial",
    path: "advanced-tutorial",
    description: "",
    visibility: "internal",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: "https://dev.renku.ch/gitlab/uploads/-/system/group/avatar/53/avatars-abstract-545599.jpg",
    request_access_enabled: false,
    full_name: "advanced-tutorial",
    full_path: "advanced-tutorial",
    parent_id: null
  },
  {
    id: 67,
    web_url: "https://dev.renku.ch/gitlab/groups/cav-sub-level1",
    name: "cav-sub-level1",
    path: "cav-sub-level1",
    description: "",
    visibility: "public",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "cav-sub-level1",
    full_path: "cav-sub-level1",
    parent_id: null
  },
  {
    id: 68,
    web_url: "https://dev.renku.ch/gitlab/groups/cav-sub-level1/cav-sub-level2",
    name: "cav-sub-level2",
    path: "cav-sub-level2",
    description: "",
    visibility: "public",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "cav-sub-level1 / cav-sub-level2",
    full_path: "cav-sub-level1/cav-sub-level2",
    parent_id: 67
  },
  {
    id: 66,
    web_url: "https://dev.renku.ch/gitlab/groups/myuser-group/myuser-gp-subgroup",
    name: "myuser-gp-subgroup",
    path: "myuser-gp-subgroup",
    description: "A subgroup of the myuser-gp group",
    visibility: "private",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "myuser-group / myuser-gp-subgroup",
    full_path: "myuser-group/myuser-gp-subgroup",
    parent_id: 42
  },
  {
    id: 42,
    web_url: "https://dev.renku.ch/gitlab/groups/myuser-group",
    name: "myuser-group",
    path: "myuser-group",
    description: "A group for projects I collaborate on.",
    visibility: "internal",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: "https://dev.renku.ch/gitlab/uploads/-/system/group/avatar/42/avatars-abstract-545599.jpg",
    request_access_enabled: false,
    full_name: "myuser-group",
    full_path: "myuser-group",
    parent_id: null
  },
  {
    id: 52,
    web_url: "https://dev.renku.ch/gitlab/groups/permissions-test",
    name: "permissions-test",
    path: "permissions-test",
    description: "A group to test out permissions.",
    visibility: "private",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "permissions-test",
    full_path: "permissions-test",
    parent_id: null
  },
  {
    id: 70,
    web_url: "https://dev.renku.ch/gitlab/groups/renku-demo",
    name: "renku-demo",
    path: "renku-demo",
    description: "Group for Renku demo projects",
    visibility: "public",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "renku-demo",
    full_path: "renku-demo",
    parent_id: null
  },
  {
    id: 51,
    web_url: "https://dev.renku.ch/gitlab/groups/renku-devs",
    name: "renku-devs",
    path: "renku-devs",
    description: "Renku core development team",
    visibility: "private",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "renku-devs",
    full_path: "renku-devs",
    parent_id: null
  },
  {
    id: 77,
    web_url: "https://dev.renku.ch/gitlab/groups/renku-external-data-one-repo",
    name: "renku-external-data-one-repo",
    path: "renku-external-data-one-repo",
    description: "One-repo external data project test",
    visibility: "internal",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: "https://dev.renku.ch/gitlab/uploads/-/system/group/avatar/77/myAvatar.png",
    request_access_enabled: false,
    full_name: "renku-external-data-one-repo",
    full_path: "renku-external-data-one-repo",
    parent_id: null
  },
  {
    id: 69,
    web_url: "https://dev.renku.ch/gitlab/groups/renku-qa",
    name: "renku-qa",
    path: "renku-qa",
    description: "Group for Renku QA and testing projects",
    visibility: "public",
    share_with_group_lock: false,
    require_two_factor_authentication: false,
    two_factor_grace_period: 48,
    project_creation_level: "developer",
    auto_devops_enabled: null,
    subgroup_creation_level: "owner",
    emails_disabled: null,
    lfs_enabled: true,
    avatar_url: null,
    request_access_enabled: false,
    full_name: "renku-qa",
    full_path: "renku-qa",
    parent_id: null
  }
];
